language: node_js

dist: trusty

cache:
  npm: true
  directories:
  - '$HOME/.sonar/cache'

services:
- xvfb

addons:
  chrome: stable
  sonarcloud:
    organization: enterpriseflowsrepository

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0

script:
- npm test -- --maxWorkers=4
- npm run build

after_success:
- sonar-scanner
- npm run coveralls

notifications:
  email:
    on_failure: change
