language: node_js

dist: trusty

cache:
  npm: true
  directories:
  - '$HOME/.sonar/cache'

services:
- xvfb

addons:
  chrome: stable
  sonarcloud:
    organization: enterpriseflowsrepository
    token:
      secure: $SONAR_TOKEN

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0

script:
- npm test -- --maxWorkers=4
- npm run build

after_success:
- npm run coveralls
- sonar-scanner -Dsonar.verbose=true -X

notifications:
  email:
    on_failure: change
