language: node_js

services:
  - xvfb

addons:
  chrome: stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

script:
  - node ./internals/scripts/generate-templates-for-linting
  - npm test -- --maxWorkers=4
  - npm run build

after_success: 'npm run coveralls'

notifications:
  email:
    on_failure: change
