steps:

# node: setup
- id: 'setup'
  name: 'gcr.io/cloud-builders/npm'
  args: ['ci']

# # node: test executions
# - id: 'test-execution'
#   name: 'gcr.io/cloud-builders/npm'
#   args: ['test', '--', '--maxWorkers=4']
#   waitFor:
#     - 'setup'

# # node: test coverage
# - id: 'test-coverage'
#   name: 'gcr.io/cloud-builders/npm'
#   args: ['run', 'coveralls']
#   waitFor:
#     - 'test-execution'

# node: build
- id: 'build'
  name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  waitFor:
  # - 'test-coverage'
  - 'setup'

# terraform: setup
- id: 'terraform-setup'
  name: 'hashicorp/terraform:0.12.13'
  args: ['init']

# terraform: deploy to gcp
- id: 'terraform-apply'
  name: 'hashicorp/terraform:0.12.13'
  args: ['apply', '--auto-approve']
  waitFor:
  - 'build'
  env:
    - 'TF_VAR_suffix=$BUILD_ID'
    - 'TF_VAR_project_id=$_PROJECT_ID'
    - 'TF_VAR_website_domain_name=$_WEBSITE_DOMAIN_NAME'
    - 'TF_VAR_create_dns_entry=$_CREATE_DNS_ENTRY'
    - 'TF_VAR_dns_managed_zone_name=$_DNS_MANAGED_ZONE_NAME'

timeout: 660s
tags: ['dashboard']
