apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: default
  labels:
    app: dashboard
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: dashboard
  type: NodePort
